.TH F3DINFO "1" "12 Nov 2011" "User Commands" "Field3D Info"
.SH NAME
f3dinfo \- Field3D Info
.SH SYNOPSIS
f3dinfo <options> 
.SH DESCRIPTION
Displays information about one or more Field3D (.f3d) file.
.SH OPTIONS
.HP
\fB\--help\fR                 Display help
.HP
\fB\--input-file arg\fR       Input files
.HP
\fB\-n [ --name ] arg\fR      Load field(s) by name
.HP
\fB\-a [ --attribute ] arg\fR Load field(s) by attribute
.SH BUGS
No known bugs for this program.
.SH AUTHOR
Magnus Wrenninge, et al. (magnus.wrenninge@gmail.com)
